### ISSUE TITLE
CAUTION: Repository replaced

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/AFileIcon#1]
As suggested by https://github.com/deathaxe/sublime-a-file-icon-old/issues/1 I folked one of the most up-to-date repos of _A File Icon_ to base my recent work on it.

This is a breaking change for those who already worked with my original repo!

Note: 

The old one is at https://github.com/deathaxe/sublime-a-file-icon-old

**Comment by evandrocoan** [comment]
You can pin this issue now with the new GitHub feature.

**Comment by deathaxe** [comment]
Removed the old repo as it should be clear now that we have moved here.
