### ISSUE TITLE
make/implement a Unity3d Icons

### ISSUE THREAD

**Issue by ShapeGroup** [SublimeText/AFileIcon#12]
a stupid thing:
Missing unity3d. Although I don't want to know how to do it because I don't understand how to insert a new icon pack.

For example, material icons become icons of Microsoft Access and are not good.

Thank you.

(congratulations, great job)

**Comment by deathaxe** [comment]
The [Unity3D packages](https://packagecontrol.io/packages/Unity3D) provides C# and JavaScript syntax files with default top scopes `source.cs` and `source.js`. Hence Unity3D specific C#/JS can't be addressed without breaking icons for existing syntaxes.

Basically the same issue exists for the [Unity Shader package](https://packagecontrol.io/packages/Unity%20Shader). It defines `source.shader` which could basically be everything.

To add unique unity icons syntaxes would need to provide a proper top-level scopes:

- `source.boo.unity3d`
- `source.cs.unity3d`
- `source.js.unity3d`
- `source.shader.unity3d`

**Comment by ShapeGroup** [comment]
OK thanks. I will try to follow the discussion.
I hope for attractive news.
Thanks =)
