### ISSUE TITLE
No icons for .editorconfig and .htaccess

### ISSUE THREAD

**Issue by francisceril** [SublimeText/AFileIcon#13]
**Environment**
macOS Mojave 10.14.5
Sublime Text v3.2.1 build 3207

Tried completely reinstalling ST3 but still **no icons** for these two files for me. It just shows the default "file icon".

**Comment by deathaxe** [comment]
Those icons show up only if the _EditorConfig_ and _ApacheConf_ packages are installed. See https://github.com/SublimeText/AFileIcon/blob/master/PACKAGES.md for the links.

If those packages are already installed, maybe one of the installed themes defines another icon name for them? I saw some themes to use `file_type_preferences` and others `file_type_apacheconf`. It depends on the theme name, which one ST picks up and uses.
