### ISSUE TITLE
Editor Config Icon

### ISSUE THREAD

**Issue by mauroreisvieira** [SublimeText/AFileIcon#17]
Hi, I have installed the EditorConfig plugin, but the icon in sidebar not change.

**Comment by deathaxe** [comment]
Does the statusbar display the `EditorConfig` syntax to be applied to the `.editorconfig` file?

Most likely you have the INI.sublime-package installed which assigns the INI.tmLanguage to that file type.

Example:

![grafik](https://user-images.githubusercontent.com/16542113/71109133-e7885680-21c4-11ea-99c5-9d8fbbbfec28.png)

**Comment by mauroreisvieira** [comment]
Hi,  I have the INI package installed.
