### ISSUE TITLE
Special icon variation for *.spec.* and *.test.* files

### ISSUE THREAD

**Issue by DavidBM** [SublimeText/AFileIcon#18]
When having test with source files icons may help a lot for identifying the files that are test and the ones that are source.

#### Expected Behavior
Files like whatever.test.ts or whatever.spec.ts should have a variation in the icon. Maybe less opacity or a tuned down color. 

#### Current Behavior
All icons, regardless of if they have .spec. or .test. have the same aperance.  

#### Possible Solution
Less opacity.
Same icon, but more greyish. 

#### Context
It helps when doing TDD when the test and the source file are in the same folder. We end with many files and that will help us to see the different file better.

**Comment by deathaxe** [comment]
Icons are assigned based on scopes. Scopes are assigned to certain file extensions. Assigning scopes to something like *.test.* is therefore not directly possible. Furthermore unittest frameworks for different languages follow different naming guidelines.

We always need to address certain languages. According to the example you want special icons for TypeScript?

**Comment by DavidBM** [comment]
Hi! I understand. There are already icons for Typescript, the problem now is this:

![image](https://user-images.githubusercontent.com/5861250/71447628-06409d00-2731-11ea-8288-d311758ecada.png)

When this grows it is difficult to check what is a test and what is source code.

But if it is not possible, then you can close this issue.
Thanks for answering! :)
