### ISSUE TITLE
Override icons

### ISSUE THREAD

**Issue by trych** [SublimeText/AFileIcon#19]
Is there an easy way to override icons?

Say I want to override all php icons and replace them by some own alternatives. I have tried the override approach that is documented somewhere, where I place a `A File Icon` folder in `Packages` and then place my pngs into the corresponding subfolder, but it does not change the icons, I guess it is still grabbing the icons in the packaged default package. Any way to work around this?

**Comment by kpym** [comment]
Yes, you can. Copy icons from `Packages\zzz A File Icon zzz` to `Packages\User` and modify them there. 
In your case the files are `file_type_php.png`, `file_type_php@2x.png` and `file_type_php@3x.png` (from `single` or from `multi` folder).

**Comment by trych** [comment]
Thanks, works perfectly.
One last question: Is it important to copy the entire `Packages/zzz A File Icon zzz` folder to `Packages/User` or can I now delete all files in there (except my new PHP icons)?

**Comment by kpym** [comment]
You don't need to copy the entire folder. You can overwrite only some icons.

**Comment by trych** [comment]
Thanks a lot for your help. Problem solved!
