### ISSUE TITLE
Lag after save

### ISSUE THREAD

**Issue by jesusferm** [SublimeText/AFileIcon#20]
Fedora 31 x86_64 32gb ram, i7 8th

3.4.4 version i file icon
3210 version sublime

The error presents on save files, after save the lag present for 2 or 3 seconds,
I removed this plugin and all work perfect.

i clean cache, index, i reinstall all clean sublime, but after install i file icons ocurred that problem

**Comment by deathaxe** [comment]
The plugin doesn't do anything when saving files.

It just creates the `zzz A File Icon zzz` package if it does not exists and then goes idle.

Maybe the indexer is still busy? The package provides a couple of alias syntaxes to be able to display all the different icons. Depending on your project's size (number of files) ST may take a while to rebuild the index after installing or updating the package.
