### ISSUE TITLE
Dockerfiles comments are not highlighted

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/AFileIcon#21]
After looking, I see my syntax is set to `YAML (Docker)` this syntax is defined for this package to give a differential icon for YAML docker files. 

![image](https://user-images.githubusercontent.com/5332158/74078743-c990e280-4a0c-11ea-88cb-7895bda4de29.png)

If I set the syntax to YAML directly, then it highlights fine:

![image](https://user-images.githubusercontent.com/5332158/74078754-e6c5b100-4a0c-11ea-9bd2-ac2778209eee.png)

But this wrapping does not seem to be working fine. This is the contents of the file:
```yaml
File: Data/Packages/zzz A File Icon zzz/aliases/YAML (Docker).sublime-syntax
 1: %YAML 1.2
 2: ---
 3: # http://www.sublimetext.com/docs/3/syntax.html
 4: name: YAML (Docker)
 5: hidden: true
 6: file_extensions:
 7:   - docker-compose.yml
 8: scope: source.yaml.docker
 9: contexts:
10:   main:
11:     - include: scope:source.yaml
12: 
```

Is there a know issue about this "push": `- include: scope:source.yaml`?

**Comment by deathaxe** [comment]
I guess it is due to https://github.com/sublimehq/sublime_text/issues/1062

**Comment by evandrocoan** [comment]
Thanks for fixing!
