### ISSUE TITLE
Incorrect icon being used for javascript

### ISSUE THREAD

**Issue by Feude** [SublimeText/AFileIcon#27]
#### Expected Behavior

A rounded-square icon is expected to be shown javascript

#### Current Behavior

A flask icon is shown

![Cap 2020-05-06 08-02-26-759](https://user-images.githubusercontent.com/51280654/81120381-f1420900-8f6f-11ea-8d76-8e88361eae66.png)

#### Steps to Reproduce (for bugs)

1. Install Sublime Text 3
2. Open Folder (for testing)
3. Install A File Icon via package control

#### Context

It's just really annoying...............

#### Your Environment

Console Output on A File Icon installation via package control

![Cap 2020-05-06 08-15-41-756](https://user-images.githubusercontent.com/51280654/81121326-cd7fc280-8f71-11ea-9c56-196465ad4978.png)

Console Output with `"dev_mode": true`

![Cap 2020-05-06 08-17-32-227](https://user-images.githubusercontent.com/51280654/81121432-1768a880-8f72-11ea-9c82-914f5965186f.png)

Just Checked `"C:\Users\<USERNAME>\AppData\Roaming\Sublime Text 3\Packages"` folder and there was only `zzz A File Icon zzz` folder, no `A File Icon` folder. So, I have downloaded a latest release and manually added it, then ran `A File Icon: Revert to a Freshly Installed State`, but didn't do any :/

**Comment by deathaxe** [comment]
That's working as expected. All files ending with `test.js` are expected test case files and thus are asigned a special icon. See: https://github.com/SublimeText/AFileIcon/issues/18
