### ISSUE TITLE
Is this package the same package downloaded through packagecontrol.io?

### ISSUE THREAD

**Issue by OdinTech3** [SublimeText/AFileIcon#3]

**Comment by deathaxe** [comment]
Yes, this is the successor of the _A File Icon_ package of ihodev. 

The PR to redirect the dead link at packagecontrol.io to this repo is still pending.

What happened:

1. It was forked from the most recent sources found on github.
2. Some dead links in the documentation were removed/renamed to match the new repository.
3. Some overhead (changelogs, build scripts, ...) have been removed or simplified a bit.
4. Icon alignment was fixed (they were all vertically off by 1)
5. Some icons from the original Atom File Icon package were added or updated

**Comment by OdinTech3** [comment]
So if i wanted to install it, I would clone the repo or what?

**Comment by deathaxe** [comment]
Would be the easiest way to install it and let Package Control keep it up to date until PR https://github.com/wbond/package_control_channel/pull/7400 is accepted.

```
cd <...>/Packages
git clone https://github.com/SublimeText/AFileIcon "A File Icon"
```

Note: This will pull the SVG sources and some files, which will not be part of the downloaded package later, but it doesn't influence functionality.

**Comment by OdinTech3** [comment]
Alright cool. I wanted to make sure this will be the main one cuz I wanted to contribute.

Thanks for the response.
