### ISSUE TITLE
Update the sublime text icon

### ISSUE THREAD

**Issue by AmjadHD** [SublimeText/AFileIcon#30]
Use the new sublime text icon https://worldvectorlogo.com/download/sublime-text.svg

**Comment by deathaxe** [comment]
Updated in 3.4.11

**Comment by AmjadHD** [comment]
@deathaxe , i read the [terms of use](https://worldvectorlogo.com/terms-of-use) of the logo in the link provided (something i seldom do) and it only allows personal use.

**Comment by deathaxe** [comment]
I didn't use your icon, but created my own one.
