### ISSUE TITLE
Update json icon

### ISSUE THREAD

**Issue by AmjadHD** [SublimeText/AFileIcon#32]
Use the new json icon https://upload.wikimedia.org/wikipedia/commons/c/c9/JSON_vector_logo.svg

**Comment by deathaxe** [comment]
Looks absolutely not like JSON. I don't think that's an improvement.

**Comment by AmjadHD** [comment]
It's used in the official site https://www.json.org/json-en.html and i saw it's used in atom, i don't know about vscode.

**Comment by deathaxe** [comment]
Maybe, doesn't change a thing.
