### ISSUE TITLE
Icons in dark themes are darker than the PNGs

### ISSUE THREAD

**Issue by nicknack23** [SublimeText/AFileIcon#33]
Possibly related to #29:  are icons in dark themes supposed to be tinted black? I would prefer to have them displayed in the original brighter colors. 

For example, the javascript PNG uses RGB(231,150,39) but is rendered in my dark theme (Adaptive theme with LastNight colors) as RGB(177,116,33).

If this is intended, could we have a setting to disable it?

**Comment by deathaxe** [comment]
A File Icon creates patches (unsupported) themes to adjust alpha channel / transparency of icons to different values for normal/hover/selected states. This makes icons darker on dark background and lighter on white, yes.

You can tweak that behavior via _A File Icon.sublime-settings_

Here are the defaults:

```
	// The opacity level of the default icon state.
	"opacity": 0.75,

	// The opacity level of the hovered icon state.
	"opacity_on_hover": 0.5,

	// The opacity level of the selected icon state.
	"opacity_on_select": 1.0,
```
