### ISSUE TITLE
No icon for TOML files

### ISSUE THREAD

**Issue by nicknack23** [SublimeText/AFileIcon#34]
I noticed you tweaked the TOML icon in a recent commit, but .toml files still display as an unknown file type for me (i.e. empty gray rectangle). I'm running v3.4.12 in Sublime 3.2.2 on Windows 10.

**Comment by deathaxe** [comment]
Icons are assigned by scope. Thus you need a syntax definition which defines the relevant scope and file extension binding.

You may want to install https://packagecontrol.io/packages/TOML.

**Comment by nicknack23** [comment]
Thanks. I absolutely don't understand the internals, but would it not be possible to fall back on file extension for unrecognized scopes? Otherwise you have to install a package for every uncommon file type even if you never need syntax highlighting for it.

**Comment by deathaxe** [comment]
That's barely possible. The only way to provide such an out-of-box experience was to ship some dummy syntax definitions (that's what A File Icon's alias syntaxes are). Unfortunatelly they tend to override the real syntax definition in case it was present (see #31).

To work around that alias syntaxes would need to be built on demand in case the real package wasn't present. It might be possible but barely worth the efforts, I think. If I work with certain kinds of files, I'd not only want to see icons but also syntax highlighting - eighther per prebaked package or selfmade.

**Comment by deathaxe** [comment]
Fixed by 3.15.0 for ST4081+

Won't fix for ST3.
