### ISSUE TITLE
no icon for harbour files (*.prg)

### ISSUE THREAD

**Issue by jvtecheto** [SublimeText/AFileIcon#36]
Hi friend 

there is no icon for language Harbour (old Clipper) , 
web site. https://harbour.github.io/

Thanks in advance.

Jose

**Comment by jvtecheto** [comment]
Thanks friend.

at first time. thanks

but you cand add or change for this package harbour. Is a fork https://github.com/rafathefull/harbour but is most active and update.
https://github.com/asistex/Sublime-Text-harbour-Package

Thanks in advance and excuse me

**Comment by deathaxe** [comment]
Thank's for the tip. It just was the first thing I found, when looking for the right scope name.

It's the intend of PACKAGES.md to show the most proper packages for users who look for.

Might be worth adding the package to https://packagecontrol.io
