### ISSUE TITLE
Test colorscheme showing up on the user's list

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/AFileIcon#38]
I am using the master branch from yesterday.

I already deleted everything and did a fresh install, but that syntax still showing up when I go to `Preferences -> Color Scheme` and scroll down to the bottom:

![image](https://user-images.githubusercontent.com/5332158/99885085-40e8d900-2c11-11eb-99bb-07354003419e.png)

I tried deleting it, but that file is not tracked by git:

![image](https://user-images.githubusercontent.com/5332158/99885154-b5237c80-2c11-11eb-96dc-8a935f981e1b.png)

**Comment by deathaxe** [comment]
This happens with cloned packages only. Test files are not shipped when installing via Package Control. Test files are empty and thus are displayed, yes. Something a developer should be able to handle.
