### ISSUE TITLE
Customize the package by adding a new icon

### ISSUE THREAD

**Issue by ArturoArciniega** [SublimeText/AFileIcon#39]
Hello!,

I'd like to add a icon for .fasta, .fa, .gff3 and .gtf files.
how can I do it?

**Comment by deathaxe** [comment]
Steps

1. Add a proper SVG image to _icons/svg_
2. Add a proper `file_type_...` entry in https://github.com/SublimeText/AFileIcon/blob/master/icons/icons.json
3. cd to _A File Icon_ directory
4. run `py build -i -p`
5. run "A File Icon: Revert to Freshly installed state" from ST's command pallete to update the `zzz A File Icon zzz` folder.

Note: 

You need cairo library to run the build scripts properly. It may be present on Linux or may be installed via package manager. 
I had to find and downlad the binary precompiled cairo.dll for Windows and place it into python's install directory.

An example to see what is needed may be [Add ADA Icon](https://github.com/SublimeText/AFileIcon/commit/fd4b0b198003183a2762d529e54192171c748729) commit.

If you have an icon and some info about the syntax or package name, I can add those easily, too. Not a big deal.

**Comment by ArturoArciniega** [comment]
Hello again,

It wil be great if you could add the icon.

The icon is [here](https://github.com/ArturoArciniega/fasta_icon/blob/master/file_type_fastq.svg)

*Information about the file format .fastq and .fasta:*

Fastq consists of a defline that contains a read identifier and possibly other information, nucleotide base calls, a second defline, and per-base quality scores, all in text form. There are many variations.

The following terms and formats are defined in general:
- Identifier and other information: text string terminated by white space
- Bases: fastq sequence should contain standard base calls (ACTGactg) or unknown bases (Nn) and can vary in length
- Qualities options:

Decimal-encoding, space-delimited: `[0-9]+ | <quality>\s[0-9]+`
Phred-33 ASCII: `[\!\"\#\$\%\&\'\(\)\*\+,\-\.\/0-9:;<=>\?\@A-I]+`
Phred-64 ASCII: `[\@A-Z\[\\\]\^_`a-h]+`

### What software use FastQ?

- Aligners
    + Bowtie, Tophat2
- Assemblers
    + Velvet, Spades
- QC tools
        Trimmomatic, FastQC

*source:* https://www.ncbi.nlm.nih.gov/sra/docs/submitformats/

**Comment by deathaxe** [comment]
Do you happen to know whether there is a syntax definition for ST already for such kinds of files?

**Comment by ArturoArciniega** [comment]
Until now there's not a Syntax in ST, I use this file format to analyze genomic data. I write scripts in bash and python programming language which have packages to handle this kind of formats.

**Comment by deathaxe** [comment]
Ok, so I'll use an alias syntax to open those file as plain text.

**Comment by ArturoArciniega** [comment]
Great!

Thanks so much!
