### ISSUE TITLE
Cant find packange in PackageControl

### ISSUE THREAD

**Issue by WiRight** [SublimeText/AFileIcon#4]
#### Expected Behavior
See package in list

#### Current Behavior
No  one

#### Possible Solution
Check ?

#### Steps to Reproduce (for bugs)
1. Install ST3
2. Install package control
3. Try install `A File Icon` with package control

#### Context
Then try installing package

#### Your Environment
Linux  4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

I know, this is not your bug, but why i could not install from package control?

**Comment by deathaxe** [comment]
The original _A File Icon_ package was deleted by the author.

The PR https://github.com/wbond/package_control_channel/pull/7400 to redirect the package in Package Control is still pending.

It would require @wbond or any other maintainer to merge the pull request to fix this issue.

**Comment by WiRight** [comment]
@deathaxe Thx for information!
fall into the waiting

**Comment by WiRight** [comment]
@deathaxe I see, your PR is merged. May i close this issue?

**Comment by deathaxe** [comment]
Note: Package Control Server seems down, atm.
