### ISSUE TITLE
Can I get your awesome Icons in VSCode?

### ISSUE THREAD

**Issue by katerlouis** [SublimeText/AFileIcon#40]
I'm surprised noone has asked this before, but I'm using VSCode for certain projects and would love to see your icons there. Is there already a package for vscode, just named differently? If not: Is there any way to achieve this?

**Comment by deathaxe** [comment]
I don't use VS Code nor have I ever contributed nor created a package for it. So I can barely answer your question.

**Comment by Hadi-Aini** [comment]
We would love to see this Icons in VSCode 👀

**Comment by smileBeda** [comment]
... this is a SublimeText package.
It uses these icons:
[Atom File Icons](https://github.com/file-icons/atom)
[Devicons](http://vorillaz.github.io/devicons/#/main)
[Font Awesome](http://fontawesome.io/)
[Font Mfizz](http://fizzed.com/oss/font-mfizz)
[Icomoon](https://icomoon.io/)
[Octicons](https://octicons.github.com/)

Not sure how VScode relates to SublimeText, but maybe you can just develop VScode using those icons?

**Comment by thoran** [comment]
@katerlouis This is about as close as you'll get without doing much work: https://github.com/file-icons/vscode.
