### ISSUE TITLE
New icon for Qt files

### ISSUE THREAD

**Issue by Antatip** [SublimeText/AFileIcon#42]
Hi, 

Having an icon for Qt files would be great !
The svg icon is available at [https://github.com/file-icons/icons/blob/master/charmap.md](https://github.com/file-icons/icons/blob/master/charmap.md).
The main color they are using for it is "#7bbc3f".

According to [this gitignore file](https://github.com/github/gitignore/blob/master/Qt.gitignore) and my experience using Qt, matching file names patterns would be: 
*.qml
*.qmlc
*.pro
*.pro.user
*.pro.user.\*
*.qbs
*.qm
*.qbs.user
*.qbs.user.\*
*.qmlproject.user
*.qmlproject.user.\*
*.pri
*.qrc
*.rcc
*.moc
moc_\*.cpp
moc_\*.h
qrc_\*.cpp
ui_\*.h
*.jsc

**Comment by deathaxe** [comment]
Not all of those extensions can be or should be bound by default.

We can't bind extensions with trailing asterisk such as `*.qmlproject.user.*`.

Other extensions such as `*.pro` or `*.moc` seem too generic and may be used in other contexts as well.

That said, the icon was added to development branch.

**Comment by Antatip** [comment]
Yeah I guess.

Thank you anyway !
