### ISSUE TITLE
Problem parsing a syntax for the terraform language

### ISSUE THREAD

**Issue by rwols** [SublimeText/AFileIcon#48]
The Terraform package (https://packagecontrol.io/packages/Terraform) apparently doesn't play well with this package

The console prints:

```
A File Icon: Cleaning up
generating syntax summary
error: Error loading syntax file "Packages/zzz A File Icon zzz/aliases/Plain Text (Terraform).sublime-syntax": Unable to read Packages/zzz A File Icon zzz/aliases/Plain Text (Terraform).sublime-syntax
A File Icon: Cleaned up successfully
```

#### Expected Behavior
No errors.

#### Current Behavior
An error :)

#### Possible Solution
I don't know.

#### Steps to Reproduce (for bugs)

1. Install Terraform package via Package Control.

#### Your Environment
ST 4104, macOS 11.2.3

**Comment by deathaxe** [comment]
The alias syntax `Packages/zzz A File Icon zzz/aliases/Plain Text (Terraform).sublime-syntax` is deleted at the next start of ST after installing Terraform package to prevent it overriding the "real" syntax.

The only error I see, when that happens is:

```
GitSavvy: could not load Packages/zzz A File Icon zzz/aliases/Plain Text (Terraform).sublime-syntax
```

But I don't know how and why GitSavvy holds a reference to that syntax or why it tries to load it.

Running the same thing on a clean setup (only A File Icon installed) doesn't produce any errors.

Maybe `sublime.find_resources("*.sublime-syntax")` still returns it even though it was just deleted, causing some plugins to get confused?

The only real issue I can imagine is a view being open with that syntax assigned. I don't think ST reassigns syntax if the alias is removed. That's something I may implement.
