### ISSUE TITLE
Installing the plugin creates another duplicate package!

### ISSUE THREAD

**Issue by 0xOpsDev** [SublimeText/AFileIcon#49]
Is it normal or its just me?

I installed the plugin and it created a new package namely "zzz A File Icon zzz". Listing the packages shows two packages viz "A File Icon" and "zzz A File Icon zzz".
![image](https://user-images.githubusercontent.com/82213558/119216176-b6b1fc80-baef-11eb-9deb-721b9f5bbfa5.png)
![image](https://user-images.githubusercontent.com/82213558/119216180-c16c9180-baef-11eb-8798-3883eede345f.png)
With it also creates a folder (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages) with the same name which is weird! I guess it should create the folder with default name as the package "A File Icon".

**Comment by deathaxe** [comment]
This is expected and required to make sure all icons correctly override those from 3rd party themes.
