### ISSUE TITLE
Add pawn languange icon

### ISSUE THREAD

**Issue by TShoKT** [SublimeText/AFileIcon#52]
When I installed this package, it did not support pawn.
It looks like a simple file (.pwn)
![dawdawdaw](https://user-images.githubusercontent.com/79834772/121775438-f58e1c00-cb9c-11eb-9deb-14c3a81e9a23.png)
Please add pawn language icon for this package. This pawn language icon is even for one of the vscode packages.
Related Links:
https://github.com/compuphase/pawn
https://github.com/pawn-lang

**Comment by deathaxe** [comment]
Please note you need a proper syntax package installed to see icons.

I found https://packagecontrol.io/packages/SourcePawn%20Syntax%20Highlighting
