### ISSUE TITLE
Adding AdonisJS icon

### ISSUE THREAD

**Issue by thetutlage** [SublimeText/AFileIcon#53]
I am not able to find any contribution guide to add a custom icon for AdonisJS ( https://adonisjs.com ). Can you please guide me how to contribute a new icon?

**Comment by deathaxe** [comment]
Is it intended to display the AdonisJS icon for .edge files of https://packagecontrol.io/packages/Edge%20templates%20extension ?

**Comment by thetutlage** [comment]
Yes and also a config file used by AdonisJS called `.adonisrc.json`

**Comment by thetutlage** [comment]
Hello. Any idea how can I go about getting it added to the package?

**Comment by deathaxe** [comment]
Icon was added by 2e30b1a275fb0abc81168ff7e4274ed56c370b5b and should be displayed for `.adonisrc.json` and `*.edge` files.

The first one requires aliases to be enabled and the latter one requires the syntax definition to be available, which provides `text.html.edge` scope.

**Comment by thetutlage** [comment]
Thanks a ton :)
