### ISSUE TITLE
graphql icons not showing

### ISSUE THREAD

**Issue by luco** [SublimeText/AFileIcon#55]
My graphql icons started to look like this a week ago:

![Captura de Tela 2021-08-16 às 09 46 58](https://user-images.githubusercontent.com/246373/129566008-41763bcc-eb3f-4d8f-a8fb-768a8fcbd1ea.png)

Do you guys know why?

**Comment by deathaxe** [comment]
GrahpQL icons have recently been added to A File Icon. Didn't exist before.

If you've seen GraphQL icons before, you most likely have a theme or package installed (other than A File Icon) which provides those.

Maybe it declares a different file type name.

Which theme are you using?

**Comment by velocityzen** [comment]
All graphql icon files are zero bytes in the package folder

<img width="818" alt="Screen Shot 2021-09-16 at 16 12 16" src="https://user-images.githubusercontent.com/451068/133679469-3559fb19-b336-4381-9b80-19507f7cc84d.png">

**Comment by deathaxe** [comment]
Those icons are intact in this repo.

You could try to run `A File Icon: Revert to Freshly Installed State` from command palette, which rebuilds the `zzz File Icon zzz` directory. If those files still don't show up correctly, you may need to reinstall the package. Maybe something got corrupted.
