### ISSUE TITLE
'Plain text (fish)' overrides the real 'Fish' syntax

### ISSUE THREAD

**Issue by eugenesvk** [SublimeText/AFileIcon#56]
I don't have any errors like those reported in this issue https://github.com/SublimeText/AFileIcon/issues/48, so not sure whether this is a duplicate.
I just have the real `Fish` syntax (from https://packagecontrol.io/packages/fish) overridden by your package's `Plain Text (Fish)` and even when I manually delete `~/Library/Application Support/Sublime Text/Packages/zzz A File Icon zzz/aliases/Plain Text (Fish).sublime-syntax`, it just gets recreated and continues to override the real `Fish` syntax.

#### Expected Behavior
A `.fish` file with a `Fish` package installed should be recognized to have a `Fish` syntax

#### Current Behavior
`Plain Text (Fish)` overrides this behavior

#### Possible Solution
Not sure since I don't entirely understand the role of these `Plain text` stubs 

#### Steps to Reproduce (for bugs)
I've tested this in a safe mode (i.e. with no other packages, caches, indexes etc):
- Launch Sublime in a safe mode
- install Package Control
- install fish package
- test that fish syntax is working on a `.fish`
- install your package
- reopen a `.fish` file and see that the syntax is `Plain Text (Fish)` instead of `Fish`

#### Context
I can't properly syntax-highlight fish config files I'm editing

#### Your Environment
ST4 4113
macOS 10.15.7

Output of `Package Settings → A File Icon → Environment` command (also available via Command Palette)
Don't have this command

<details>
  <summary>ST Console output (`View → Show Console`) with `"dev_mode": true` option in A File Icon.sublime-settings</summary>
```
A File Icon: Initializing settings
A File Icon: Initializing icons
         >>> All the necessary icons are provided
A File Icon: Getting installed themes
         >>> {'Theme - Default': ['Adaptive.sublime-theme', 'Default Dark.sublime-theme', 'Default.sublime-theme'], 'ayu': ['ayu-dark.sublime-theme', 'ayu-light.sublime-theme', 'ayu-mirage.sublime-theme'], 'Material Theme': ['Material-Theme-Darker.sublime-theme', 'Material-Theme-Lighter.sublime-theme', 'Material-Theme-Palenight.sublime-theme', 'Material-Theme.sublime-theme'], 'Seti_UI': ['Seti.sublime-theme', 'Seti_orig.sublime-theme']}
A File Icon: Getting the list of theme packages with customization support
         >>> {'Material Theme', 'ayu'}
A File Icon: Preparing general patch
         >>> [{'class': 'icon_file_type', 'layer0.tint': None, 'layer0.opacity': 0.9, 'content_margin': [8, 8]}, {'class': 'icon_file_type', 'layer0.tint': None, 'parents': [{'class': 'tree_row', 'attributes': ['hover']}], 'layer0.opacity': 0.7}, {'class': 'icon_file_type', 'layer0.tint': None, 'parents': [{'class': 'tree_row', 'attributes': ['selected']}], 'layer0.opacity': 1.0}]
A File Icon: Preparing specific patch
         >>> [{'class': 'icon_file_type', 'layer0.tint': None}]
A File Icon: Patching themes
A File Icon: Ignored `Adaptive.sublime-theme`
A File Icon: Ignored `Default Dark.sublime-theme`
A File Icon: Ignored `Default.sublime-theme`
A File Icon: Checking icons for ayu...
A File Icon: Ignored `ayu-dark.sublime-theme`
A File Icon: Ignored `ayu-light.sublime-theme`
A File Icon: Ignored `ayu-mirage.sublime-theme`
A File Icon: Checking icons for Material Theme...
A File Icon: Ignored `Material-Theme-Darker.sublime-theme`
A File Icon: Ignored `Material-Theme-Lighter.sublime-theme`
A File Icon: Ignored `Material-Theme-Palenight.sublime-theme`
A File Icon: Ignored `Material-Theme.sublime-theme`
A File Icon: Ignored `Seti.sublime-theme`
A File Icon: Ignored `Seti_orig.sublime-theme`
A File Icon: Removing obsolete theme patches
A File Icon: Updating aliases
```
</details>

**Comment by deathaxe** [comment]
It turned out, A File Icon assumed the wrong main scope `source.fish`. It is corrected to `source.shell.fish`.

A new release is cut and should arive soon via Package Control automatically.

The dummy syntax `Plain Text (Fish)` will be removed upon next start of ST after upgrade to 3.15.12.
