### ISSUE TITLE
A few missing icons

### ISSUE THREAD

**Issue by christopherpickering** [SublimeText/AFileIcon#61]
Thanks for this,

I have a few dot files missing icons. Should there be icons for them as well?

- .coverage
- .htmlhintrc
- .jshintignore
- .prettierignore
- .prettierrc
- .releaserc
- *.sqlite

Thanks!

**Comment by deathaxe** [comment]
A File Icon provides an icon for SQL files, already. To display sqlite files with it, the extension needs to be bound to SQL syntax via _Allways open With... > SQL_.

I am uncertain about a good icon for _.coverage_ files. Not even sure about the content. Seems to be a binary file used by MS tools.

**Comment by deathaxe** [comment]
All added in 3.17.0

**Comment by christopherpickering** [comment]
Thanks!
