### ISSUE TITLE
Jest configuration files

### ISSUE THREAD

**Issue by QuestionMark3** [SublimeText/AFileIcon#62]
Hi,

Is it possible to add icons for jest.* files?
For example jest.config.js and jest.setup.ts

**_Some sample icons I made:_**

**Multi**
![multi file_type_jest@3x](https://user-images.githubusercontent.com/32991975/201546744-05feb704-6c54-40be-929a-1c11fccf2637.png) ![multi file_type_jest@2x](https://user-images.githubusercontent.com/32991975/201546745-9f7135b3-c256-4d48-a7f8-5b3cb1cfd8cf.png) ![multi file_type_jest](https://user-images.githubusercontent.com/32991975/201546746-b528926b-f602-4092-a42a-1d8ad5acc493.png)

**Multi with outline**
![border file_type_jest@3x](https://user-images.githubusercontent.com/32991975/201546743-feb1ed1d-e8e8-4e2b-be28-e2ef7de1a82a.png) ![border file_type_jest@2x](https://user-images.githubusercontent.com/32991975/201546742-d9b1b2a7-71f8-4c8e-97e1-1678b08ca149.png) ![border file_type_jest](https://user-images.githubusercontent.com/32991975/201546741-6e71fae7-5685-4626-be2f-de0f6d44cf95.png)

**Single**
![single file_type_jest@3x](https://user-images.githubusercontent.com/32991975/201546747-d28268e8-c855-469b-8f41-26433794c41c.png) ![single file_type_jest@2x](https://user-images.githubusercontent.com/32991975/201546748-5ffaab61-70d7-410c-8032-22a31f4eb001.png) ![single file_type_jest](https://user-images.githubusercontent.com/32991975/201546749-985b129d-ce1a-4d6e-883f-038539a13124.png)

Thanks!

**Comment by deathaxe** [comment]
Adding the icon is no problem.

Globs like `jsest.*` can't however be bound. A full extension name such as `jest.setup.ts` is required.

**Comment by QuestionMark3** [comment]
Thanks!

According to the [docs](https://jestjs.io/docs/configuration), the jest configuration can also be `jest.config.json`
Could `JSON (Jest)` be added for completion's sake?
