### ISSUE TITLE
Extend json icon to jsonc file extension

### ISSUE THREAD

**Issue by will-wright-eng** [SublimeText/AFileIcon#63]
Great package so thanks in advance for supporting! I've come across a file without an icon: `.markdownlint.jsonc` ([source](https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.jsonc))

- It looks like the `.jsonc` file extension is supported by [Atom File Icon](https://github.com/file-icons/atom/search?q=jsonc) but I couldn't find any references to it in this repo
- It seems to have been around for a while based on [this SO post](https://stackoverflow.com/questions/14851903/what-is-jsonc-are-jsonc-and-json-c-different) 

Is there a setting I can change in package control or sublime text itself in order for `.jsonc` files to adopt the `.json` icon by default? Alternatively, would you like me to open a PR for this?

**Comment by deathaxe** [comment]
It's enough to assign to assign *.jsonc file extenstion to JSON syntax via "Open all with current extension as..." sub menu.

**Comment by will-wright-eng** [comment]
Perfect! Thank you
