### ISSUE TITLE
[Question] Same icon, different colour

### ISSUE THREAD

**Issue by mataha** [SublimeText/AFileIcon#66]
Is it possible to provide a different colour for an alias of an icon?

**Context:** I want to submit a PR that will add an icon for `source.Kotlin.gradle` scope, but I'd like it to have both the colour of `file_type_kotlin` and the icon of `file_type_gradle` to match the behaviour of other editors, e.g. IntelliJ IDEA. Is there a clean way of doing so without declaring a new filetype?

Specifically I'd like to avoid this:

```json
  "file_type_gradle_kotlin": {
    "aliases": [
      {
        "base": "source.Kotlin",
        "extensions": [
          "gradle.kts"
        ],
        "name": "Kotlin (Gradle)",
        "scope": "source.Kotlin.gradle"
      }
    ],
    "color": "blue"
  }
```

As both Gradle and Kotlin are covered already.

**Comment by mataha** [comment]
Variant 1 looks better indeed and is in line with Gradle Groovy scripts (`source.groovy.gradle`).

> Some notes/suggestions:
> 
> 1. scope names should be lower case (`source.kotlin.gradle`).
> 2. file type name and scope name parts should be in same order. The oder depends on whether kotlin is interpreted as a dialect/special case of gradle or vise versa.

1. Kotlin is capitalized everywhere in the code, should I correct that in my PR?
2. Got it, `file_type_kotlin_gradle` it is then.

**Comment by deathaxe** [comment]
As the original Kotlin syntax uses capital `K`, you should probably better keep going with it. Otherwise we might run into casing issues.
