### ISSUE TITLE
Add support for bun

### ISSUE THREAD

**Issue by mauroreisvieira** [SublimeText/AFileIcon#73]
Bun is a JavaScript runtime & toolkit designed for speed, complete with a bundler, that can replace the NPM, I would like to know if is possible to add support for that.

**Icon:**

![bun](https://github.com/SublimeText/AFileIcon/assets/3084774/f349ff62-4b56-4c88-a540-0daf4d8c55d1)

**Extensions Support:**
https://github.com/vscode-icons/vscode-icons/pull/3077/files

**Comment by deathaxe** [comment]
Do you know off hand, which syntax `bun` files use?

**Comment by deathaxe** [comment]
Added in 3.25.0
