### ISSUE TITLE
System icons for macOS and other OS

### ISSUE THREAD

**Issue by schrodincat** [SublimeText/AFileIcon#9]
Lack of icons in the app sidebar is not the only issue with icons in Sublime Text. System icons are also very limited and bland. Here is example on macOS:
<img width="911" alt="screenshot 2019-02-07 at 04 36 30" src="https://user-images.githubusercontent.com/13354491/52385390-620b2480-2a92-11e9-9b95-9cd8ff2d1930.png">
How nice would it be if the package could repurpose those beautiful icons we already have to act as a system icons? Is it even possible to do?

I know it's probably stretching the limits of this project scale, but I feel like this question is interesting enough to be discussed at least.

**Comment by capripot** [comment]
That's a good idea!

Do you think we could get 512x512px versions of all icons?

**Comment by deathaxe** [comment]
I don't think it's within the scope of _A File Icon_ to provide file type specific icons for applications other than Sublime Text.

Furthermore I doubt the current set of quite simple icons to look well when used in the AppFinder or Windows Explorer.

**Comment by ahmu83** [comment]
Is there an alternative way to assign icons for file types in the finder window?

**Comment by schrodincat** [comment]
@ahmu83 it needs to be donated by some app, you can make dummy app just for that, I guess
